language: go
go:
  - 1.x

env:
  global:
    - SCYLLA_OPTS="--developer-mode 1 --enable-in-memory-data-store 1 --log-to-stdout 1 --default-log-level info"
  matrix:
    - DB="scylla"
    - DB="cassandra"

sudo: true

dist: trusty
addons:
  apt:
    packages:
      - moreutils

before_install:
  - ./.travis_start_db.sh

install:
  - make get-deps
  - make get-tools

script:
  - make
